CREATE TABLE `sys_api_log` (
   `id` varchar(32) NOT NULL,
   `model` varchar(50) CHARACTER SET utf8 DEFAULT NULL COMMENT '类型 IN-本系统对外api or OUT-调的外部接口',
   `current_system` varchar(50) CHARACTER SET utf8 DEFAULT NULL COMMENT '接口调用的系统名称',
   `req_type` varchar(50) CHARACTER SET utf8 DEFAULT NULL COMMENT '请求类别，QUERY，INSERT，UPDATE，DELETE',
   `provider` varchar(40) CHARACTER SET utf8 DEFAULT NULL COMMENT '接口提供方',
   `url` varchar(500) CHARACTER SET utf8 DEFAULT NULL COMMENT '请求接口路径',
   `request` text CHARACTER SET utf8 COMMENT '请求信息',
   `result` text CHARACTER SET utf8 COMMENT '返回结果',
   `deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除',
   `created_by` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
   `created_time` datetime DEFAULT NULL COMMENT '创建时间',
   `updated_by` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人',
   `updated_time` datetime DEFAULT NULL COMMENT '更新时间',
   `ip_addr` varchar(64) DEFAULT NULL COMMENT '请求的ip地址',
   `is_exception` varchar(2) DEFAULT NULL COMMENT '系统调用是否异常，1-是，0-否',
   `param_type_name` varchar(500) DEFAULT NULL COMMENT '参数类型',
   `success_str` varchar(100) DEFAULT NULL COMMENT '成功标识',
   `route_name` varchar(50) DEFAULT NULL COMMENT '路由地址',
   PRIMARY KEY (`id`) USING BTREE,
   KEY `created_time_idx` (`created_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='api请求日志记录表'